// src/app/terms-conditions/page.tsx
import Head from 'next/head';
import Link from 'next/link';
import Container from '../_components/Container';

export default function TermsAndConditionsPage() {
    return (
        <Container>
            <Head>
                <title>Terms and Conditions - Vasilkoff</title>
                <meta
                    name="description"
                    content="Read the terms and conditions that govern your use of Vasilkoff's services. Understand your rights and obligations when engaging with our mobile apps and web-development solutions."
                />
            </Head>

            <article className="pt-40 md:py-[100px]">
                <h1 className="pb-5 text-3xl font-bold text-secondary sm:text-4xl">Terms and Conditions</h1>
                <p>Last updated: March 18, 2024</p>
                <div className="pb-12 my-10 space-y-2">
                    <p>
                        Welcome to Vasilkoff.com, the website representing Vasilkoff CY Ltd and Vasilkoff Ltd, companies registered in Cyprus and the United Kingdom. Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the Vasilkoff.com website (the "Service") operated by Vasilkoff CY Ltd and Vasilkoff Ltd ("us", "we", or "our").
                    </p>
                    <p>
                        Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
                    </p>
                    <p>
                        By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
                    </p>
                    <h2>Intellectual Property</h2>
                    <p>
                        All content on this website, including but not limited to text, images, graphics, logos, and software, is the property of Vasilkoff CY Ltd, Vasilkoff Ltd, or its content suppliers and is protected by international copyright laws.
                    </p>
                    <h2>Permitted Use</h2>
                    <p>
                        You are granted a limited, non-exclusive, non-transferable, and revocable license to access and use the Service for personal, non-commercial purposes only. You may not modify, distribute, transmit, or create derivative works based on the content of this website without the express written consent of Vasilkoff CY Ltd and Vasilkoff Ltd.
                    </p>
                    <h2>Prohibited Use</h2>
                    <p>
                        You agree not to use the Service for any unlawful or prohibited purpose, or to solicit others to perform or participate in any unlawful acts. You may not use the Service in any manner that could damage, disable, overburden, or impair the Service or interfere with any other party's use and enjoyment of the Service.
                    </p>
                    <h2>External Links</h2>
                    <p>
                        Our Service may contain links to third-party websites or services that are not owned or controlled by Vasilkoff CY Ltd and Vasilkoff Ltd. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that Vasilkoff CY Ltd and Vasilkoff Ltd shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such websites or services.
                    </p>
                    <h2>Analytics</h2>
                    <p>
                        We use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
                    </p>
                    <h2>Mobile Applications</h2>
                    <p>
                        Our mobile applications are available on Google Play and the Apple App Store. By downloading and using our mobile applications, you agree to comply with the terms and conditions of the respective application stores and any additional terms and conditions applicable to the mobile applications.
                    </p>
                    <h2>Changes to Terms</h2>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
                    </p>
                    <h2>Disclaimer</h2>
                    <p>
                        The information on this website is provided on an "as is" basis. Vasilkoff CY Ltd and Vasilkoff Ltd make no representations or warranties of any kind, express or implied, as to the operation of this website, the information, content, materials, or products included on this website. To the full extent permissible by applicable law, Vasilkoff CY Ltd and Vasilkoff Ltd disclaim all warranties, express or implied, including but not limited to, implied warranties of merchantability and fitness for a particular purpose. Vasilkoff CY Ltd and Vasilkoff Ltd will not be liable for any damages of any kind arising from the use of this website, including but not limited to direct, indirect, incidental, punitive, and consequential damages.
                    </p>
                    <h2>Governing Law</h2>
                    <p>
                        These Terms shall be governed and construed in accordance with the laws of Cyprus and the United Kingdom, without regard to their conflict of law provisions. Any disputes relating to these Terms or the use of the Service shall be subject to the exclusive jurisdiction of the courts of Cyprus and the United Kingdom.
                    </p>
                    <h2>Contact Us</h2>
                    <p>
                        If you have any questions or concerns regarding these Terms, please feel free to reach out to us via our <Link href="/contact-us">Contact Us</Link> page.
                    </p>
                </div>
                <p className="text-secondary font-bold border-t border-secondary">
                    By using our website and/or mobile applications, you acknowledge that you have read and understood these Terms and Conditions and agree to be bound by them.
                </p>
            </article>
        </Container>
    );
}
