import { useSelector } from 'react-redux';
import { IRootState } from '../store';
import Head from 'next/head';
import { Container } from 'react-bootstrap';
import Link from 'next/link';

const Privacypolicy = () => {

    return (
        <>
            <Head>
                <title>Privacy Policy - Vasilkoff</title>
                <meta 
                    name="description" 
                    content="This Privacy Policy outlines how Vasilkoff collects, uses, and manages your information. Your privacy is our top priority." 
                />
            </Head>
            <div className="pt-40 md:py-[100px]">
                <div className="container">
                    <h2 className="pb-5 text-xl font-bold text-black sm:text-2xl">Terms and Conditions</h2>

                    <p>Last updated: April 18, 2023</p>
                    <div className="pb-12 my-10 space-y-2 prose">
                        <p>
                    Vasilkoff CY Ltd and Vasilkoff Ltd ("us", "we", or "our") operate the Vasilkoff.com website (the "Service") and are committed to protecting the privacy of our users. This Privacy Policy explains the types of information we collect, how we use it, and your rights regarding your information.
</p><p>
By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
</p>
<ol>
<li>
Information We Collect
While using our Service, we may collect non-personally identifiable information through Google Analytics. This information may include, but is not limited to:
<ul>
<li>
Your computer's Internet Protocol (IP) address
</li><li>
Browser type and version
</li><li>
The pages of our Service that you visit
</li><li>
The time and date of your visit
</li><li>
Time spent on those pages
</li><li>
Other diagnostic data
</li>
</ul>
</li><li>
How We Use Your Information
We use the collected information for various purposes, including:
<ul>
<li>
To monitor and analyze the usage of our Service
</li><li>
To improve the functionality and user experience of our Service
</li><li>
To ensure the security and integrity of our Service
</li>
</ul>
</li><li>
Google Analytics<br/>
We use Google Analytics to collect, monitor, and analyze the usage of our Service. Google Analytics is a web analytics service provided by Google, Inc. ("Google"). The information generated by the cookie about your use of the Service (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information to evaluate your use of the Service, compile reports on website activity for website operators, and provide other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
<br/>
By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
</li><li>
Mobile Applications<br/>
Our mobile applications are available on Google Play and the Apple App Store. When you download and use our mobile applications, the respective application stores may collect certain information about you, such as your device information, app usage data, and other diagnostic information. This information is subject to the privacy policies of the respective application stores and is not covered by this Privacy Policy.
</li><li>
Security<br/>
The security of your information is important to us. We employ commercially acceptable means to protect your information, but please be aware that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee its absolute security.
</li><li>
Changes to This Privacy Policy<br/>
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
<br/>
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
</li><li>
Your Rights<br/>
You have the right to access, correct, or delete any personal information we hold about you. To exercise these rights, please contact us at  <Link href="mailto:sp@vasilkoff.com">sp@vasilkoff.com</Link>.
</li><li>
Contact Us<br/>
If you have any questions or concerns regarding this Privacy Policy, please do not hesitate to reach out to us through our <Link href="/contact-us">Contact Us</Link> page.
</li>
</ol>
                    </div>

                </div>
            </div>
        </>
    )
}

export default Privacypolicy;
