import { useSelector } from 'react-redux';
import { IRootState } from '../store';
import Head from 'next/head';

const Termsandcondition = () => {
    const isRtl = useSelector((state: IRootState) => state.themeConfig.direction) === 'rtl' ? true : false;

    return (
        <div>
            <Head>
                <title>Terms and Conditions</title>
            </Head>

            <div className="py-40 md:py-[100px]">
                <div className="container">
                    <div className="pb-12 my-20">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Terms and Conditions</h4>
                        <p className="pb-5 text-lg font-medium">
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the
                            amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This
                            electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            his document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines)
                            Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of
                            careers.padme.com, life. padme.com & blog.padme.com website.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            This Website, including all Materials present (excluding any applicable third party materials), is the property of Myntra and is
                            copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws
                            worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree
                            to take all of the terms and conditions stated on this page.
                        </p>
                        <p className="text-lg font-medium">
                            The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements:
                            “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The
                            Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and
                            ourselves.
                        </p>
                    </div>
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Cookies</h4>
                        <p className="pb-5 text-lg font-medium">
                            We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy
                            Policy.
                        </p>
                        <p className="text-lg font-medium">
                            Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to
                            enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising
                            partners may also use cookies.
                        </p>
                    </div>
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">License</h4>
                        <p className="pb-5 text-lg font-medium">
                            Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name.
                            All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to
                            restrictions set in these terms and conditions.
                        </p>
                        <h6 className="pb-2 font-semibold text-black">You must not:</h6>
                        <ul className="pb-5 text-lg font-medium">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Republish material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Sell, rent or sub-license material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Reproduce, duplicate or copy material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Redistribute content from Website Name
                            </li>
                        </ul>
                        <p className="pb-5 text-lg font-medium">This Agreement shall begin on the date hereof.</p>
                        <p className="pb-5 text-lg font-medium">
                            Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website.
                            Company Name does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the
                            views and opinions of Company Name,its agents and/or affiliates. Comments reflect the views and opinions of the person who post
                            their views and opinions.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive
                            or causes breach of these Terms and Conditions.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive
                            or causes breach of these Terms and Conditions.
                        </p>
                        <h6 className="pb-2 font-semibold text-black">You warrant and represent that:</h6>
                        <ul className="pb-5 text-lg font-medium ltr:pl-1 rtl:pr-1">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any
                            </li>
                        </ul>
                        <h6 className="pb-2 font-semibold text-black">Third party;</h6>
                        <ul className="pb-5 text-lg font-medium ltr:pl-1 rtl:pr-1">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of
                                privacy
                            </li>
                        </ul>
                        <p className="text-lg font-medium">
                            You hereby grant Company Name a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of
                            your Comments in any and all forms, formats or media.
                        </p>
                    </div>
                    <div>
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Hyperlinking to our Content</h4>
                        <p className="pb-5 text-lg font-medium">The following organizations may link to our Website without prior written approval:</p>
                        <ul className="pb-5 text-lg font-medium">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Government agencies;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Search engines;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                News organizations;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed
                                businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and
                                charity fundraising groups
                            </li>
                        </ul>
                        <p className="text-lg font-medium">which may not hyperlink to our Web site.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Termsandcondition;
